### ISSUE TITLE
进行到配置qq_bot_core.py时，始终无法运行

### ISSUE THREAD

**Issue by CRxl0** [remiliacn/qqBot#17]
报错如下：
Traceback (most recent call last):
  File "C:\Users\13712\Downloads\qqBot-master\qq_bot_core.py", line 10, in <module>
    from Services.cangku_api import CangkuApi
  File "C:\Users\13712\Downloads\qqBot-master\Services\cangku_api.py", line 8, in <module>
    from config import CANGKU_USERNAME, CANGKU_PASSWORD
ImportError: cannot import name 'CANGKU_USERNAME' from 'config' (unknown location)

已经在qq_bot_core.py中设置了CANGKU_USERNAME
这不就变成了因为没有CANGKU_USERNAME，所以要运行qq_bot_core.py去设置，
但又因为没有CANGKU_USERNAME，所以运行不了qq_bot_core.py的死循环？

**Comment by CRxl0** [comment]
这样就算跑起来了吗？

[2022-03-08 17:22:28,327 nonebot] ERROR: Failed to import "awesome.plugins.get_tweet", error: cannot import name 'PATH_TO_ONEDRIVE' from 'config' (C:\Users\13712\Downloads\qqBot-master\config.py)
[2022-03-08 17:22:28,327 nonebot] ERROR: cannot import name 'PATH_TO_ONEDRIVE' from 'config' (C:\Users\13712\Downloads\qqBot-master\config.py)
Traceback (most recent call last):
  File "D:\python3.9\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "D:\python3.9\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\13712\Downloads\qqBot-master\awesome\plugins\get_tweet\__init__.py", line 1, in <module>
    from . import get_tweet
  File "C:\Users\13712\Downloads\qqBot-master\awesome\plugins\get_tweet\get_tweet.py", line 15, in <module>
    from config import SUPER_USER, DOWNLODER_FILE_NAME, PATH_TO_ONEDRIVE
ImportError: cannot import name 'PATH_TO_ONEDRIVE' from 'config' (C:\Users\13712\Downloads\qqBot-master\config.py)
[2022-03-08 17:22:28,778 nonebot] WARNING: Plugins successfully installed.
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: True
 * Running on http://127.0.0.1:5700 (CTRL + C to quit)
[2022-03-08 17:22:28,878] Running on http://127.0.0.1:5700 (CTRL + C to quit)

**Comment by CRxl0** [comment]
而且还有个问题，这个qqbot是怎么和go-cqhttp联系起来的，感觉就是两个完全分离的系统

**Comment by CRxl0** [comment]
我把qqbot和go-cqhttp的config文件里的网址都设置成127.0.0.1：5701后就出现了这种报错

[2022-03-08 17:52:10,689 nonebot] ERROR: Failed to import "awesome.plugins.get_tweet", error: cannot import name 'PATH_TO_ONEDRIVE' from 'config' (C:\Users\13712\Downloads\qqBot-master\config.py)
[2022-03-08 17:52:10,689 nonebot] ERROR: cannot import name 'PATH_TO_ONEDRIVE' from 'config' (C:\Users\13712\Downloads\qqBot-master\config.py)
Traceback (most recent call last):
  File "D:\python3.9\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "D:\python3.9\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\13712\Downloads\qqBot-master\awesome\plugins\get_tweet\__init__.py", line 1, in <module>
    from . import get_tweet
  File "C:\Users\13712\Downloads\qqBot-master\awesome\plugins\get_tweet\get_tweet.py", line 15, in <module>
    from config import SUPER_USER, DOWNLODER_FILE_NAME, PATH_TO_ONEDRIVE
ImportError: cannot import name 'PATH_TO_ONEDRIVE' from 'config' (C:\Users\13712\Downloads\qqBot-master\config.py)
[2022-03-08 17:52:11,094 nonebot] WARNING: Plugins successfully installed.
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: True
 * Running on http://127.0.0.1:5701 (CTRL + C to quit)
Traceback (most recent call last):
  File "C:\Users\13712\Downloads\qqBot-master\qq_bot_core.py", line 139, in <module>
    main()
  File "C:\Users\13712\Downloads\qqBot-master\qq_bot_core.py", line 123, in main
    nonebot.run()
  File "D:\python3.9\lib\site-packages\nonebot\__init__.py", line 116, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "D:\python3.9\lib\site-packages\nonebot\__init__.py", line 61, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "D:\python3.9\lib\site-packages\aiocqhttp\__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "D:\python3.9\lib\site-packages\quart\app.py", line 1671, in run
    loop.run_until_complete(task)
  File "D:\python3.9\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\python3.9\lib\site-packages\hypercorn\asyncio\__init__.py", line 41, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "D:\python3.9\lib\site-packages\hypercorn\asyncio\run.py", line 88, in worker_serve
    sockets = config.create_sockets()
  File "D:\python3.9\lib\site-packages\hypercorn\config.py", line 196, in create_sockets
    insecure_sockets = self._create_sockets(self.bind)
  File "D:\python3.9\lib\site-packages\hypercorn\config.py", line 259, in _create_sockets
    sock.bind(binding)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

**Comment by remiliacn** [comment]
更新了下README，看这里
https://github.com/remiliacn/qqBot#config
