### ISSUE TITLE
启动过程中无法启动，根据qq_bot_core.py中的提示注释掉第9行后仍无法启动

### ISSUE THREAD

**Issue by cdromcdrom** [remiliacn/qqBot#21]
已添加config.py并填写了内容，启动qq_bot_core.py失败
以下为报错内容

> C:\Users\Administrator\Desktop\robot\qqBot-3.0.0\qqBot-3.0.0>python qq_bot_core.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\robot\qqBot-3.0.0\qqBot-3.0.0\qq_bot_core.py", line 143, in <module>
    main()
  File "C:\Users\Administrator\Desktop\robot\qqBot-3.0.0\qqBot-3.0.0\qq_bot_core.py", line 118, in main
    nonebot.init(config)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 81, in init
    _bot = NoneBot(config_object)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 35, in __init__
    self.asgi.debug = self.config.DEBUG
AttributeError: module 'config' has no attribute 'DEBUG'

不排除自身库安装问题

**Comment by remiliacn** [comment]
试一下在config文件第一行加上这个

```
from nonebot.default_config import *
```

**Comment by cdromcdrom** [comment]
> 试一下在config文件第一行加上这个
> 
> ```
> from nonebot.default_config import *
> ```

问题解决了，感谢
