### ISSUE TITLE
在进行部署时遇到了未知问题

### ISSUE THREAD

**Issue by 1bobsy** [remiliacn/qqBot#25]
大佬，我这边尝试部署的时候出现了这个错误，请问一下这个错误要怎么解决，

我这边也有创建config.py这个文件，但是只配置了超管和端口，也没进行其他配置

PS F:\boot\2\3\qqBot-3.0.0> python qq_bot_core.py
Traceback (most recent call last):
  File "qq_bot_core.py", line 143, in <module>
    main()
  File "qq_bot_core.py", line 118, in main
    nonebot.init(config)
NameError: name 'config' is not defined

下面这个是我直接解压下来还没进行任何操作直接运行的报错

PS F:\boot\2\qqBot-3.0.0> python qq_bot_core.py
Traceback (most recent call last):
  File "qq_bot_core.py", line 10, in <module>
    from Services.cangku_api import CangkuApi
  File "F:\boot\2\qqBot-3.0.0\Services\cangku_api.py", line 8, in <module>
    from config import CANGKU_USERNAME, CANGKU_PASSWORD
ImportError: cannot import name 'CANGKU_USERNAME' from 'config' (unknown location)

**Comment by remiliacn** [comment]
就算用不到的配置也不能删掉。
