### ISSUE TITLE
运行时不时会报错

### ISSUE THREAD

**Issue by sola614** [remiliacn/qqBot#5]
时不时会报这个错：
```
INFO: Doing video fetch...
Job "send_tweet (trigger: interval[0:00:50], next run at: 2021-09-23 15:55:12 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/get_tweet/get_tweet.py", line 119, in send_tweet
    Popen(
  File "/usr/local/python3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'py'
```
用的python版本是3.9.7

**Comment by sola614** [comment]
原来是我CQHTTP的链接方式没选对，要选`反向 Websocket 通信`然后再配置里的universal填上` ws://127.0.0.1:5700/ws/`

**Comment by remiliacn** [comment]
看起来是自动下源的问题，你可以尝试把下面这部分代码删了：
https://github.com/remiliacn/qqBot/blob/13a44b0517f8fab1629827da121e48c24da97b31/awesome/plugins/get_tweet/get_tweet.py#L122-L130

或者把这行里的`py`改成`python`试试
https://github.com/remiliacn/qqBot/blob/13a44b0517f8fab1629827da121e48c24da97b31/awesome/plugins/get_tweet/get_tweet.py#L125

**Comment by sola614** [comment]
启动的时候报了这些错误
```
python ./qq_bot_core.py 
[2021-09-25 18:12:39,271 nonebot] INFO: Succeeded to import and load "awesome.plugins.games"
[2021-09-25 18:12:39,272 nonebot] INFO: Succeeded to import and load "awesome.plugins.admin_setting"
[2021-09-25 18:12:39,273 nonebot] INFO: Succeeded to import and load "awesome.plugins.chitchat"
[2021-09-25 18:12:39,273 nonebot] INFO: Succeeded to import and load "awesome.plugins.shadiao"
[2021-09-25 18:12:39,367 nonebot] INFO: Succeeded to import and load "awesome.plugins.get_tweet"
[2021-09-25 18:12:39,374 nonebot] ERROR: Failed to import and load "awesome.plugins.setu", error: cannot import name 'cangku_api' from 'qq_bot_core' (/root/qqbot/qqBot-2.0.0/qq_bot_core.py)
[2021-09-25 18:12:39,374 nonebot] ERROR: cannot import name 'cangku_api' from 'qq_bot_core' (/root/qqbot/qqBot-2.0.0/qq_bot_core.py)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/setu/__init__.py", line 1, in <module>
    from . import setu
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/setu/setu.py", line 16, in <module>
    from qq_bot_core import sanity_meter, user_control_module, admin_control, cangku_api
ImportError: cannot import name 'cangku_api' from 'qq_bot_core' (/root/qqbot/qqBot-2.0.0/qq_bot_core.py)
[2021-09-25 18:12:39,384 nonebot] ERROR: Failed to import and load "awesome.plugins.little_helper", error: No module named 'Services.okex'
[2021-09-25 18:12:39,384 nonebot] ERROR: No module named 'Services.okex'
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/little_helper/__init__.py", line 1, in <module>
    from . import little_helper
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/little_helper/little_helper.py", line 10, in <module>
    from Services.stock import Stock, Crypto
  File "/root/qqbot/qqBot-2.0.0/Services/stock.py", line 12, in <module>
    import Services.okex.spot_api as spot
ModuleNotFoundError: No module named 'Services.okex'
[2021-09-25 18:12:39,385 nonebot] ERROR: Failed to import and load "awesome.plugins.notice_handler", error: cannot import name 'notice_handler' from partially initialized module 'awesome.plugins.notice_handler' (most likely due to a circular import) (/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py)
[2021-09-25 18:12:39,385 nonebot] ERROR: cannot import name 'notice_handler' from partially initialized module 'awesome.plugins.notice_handler' (most likely due to a circular import) (/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py", line 1, in <module>
    from . import notice_handler
ImportError: cannot import name 'notice_handler' from partially initialized module 'awesome.plugins.notice_handler' (most likely due to a circular import) (/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py)
[2021-09-25 18:12:39,386 nonebot] ERROR: Failed to import and load "awesome.plugins.natural_language", error: cannot import name 'cangku_api' from 'qq_bot_core' (/root/qqbot/qqBot-2.0.0/qq_bot_core.py)
[2021-09-25 18:12:39,386 nonebot] ERROR: cannot import name 'cangku_api' from 'qq_bot_core' (/root/qqbot/qqBot-2.0.0/qq_bot_core.py)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/natural_language/__init__.py", line 1, in <module>
    from . import natural_language
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/natural_language/natural_language.py", line 11, in <module>
    from awesome.plugins.setu.setu import sauce_helper
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/setu/__init__.py", line 1, in <module>
    from . import setu
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/setu/setu.py", line 16, in <module>
    from qq_bot_core import sanity_meter, user_control_module, admin_control, cangku_api
ImportError: cannot import name 'cangku_api' from 'qq_bot_core' (/root/qqbot/qqBot-2.0.0/qq_bot_core.py)
[2021-09-25 18:12:39,386 nonebot] WARNING: Plugins successfully installed.
[2021-09-25 18:12:39,386 nonebot] INFO: Running on 127.0.0.1:5700
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: True
 * Running on http://127.0.0.1:5700 (CTRL + C to quit)
[2021-09-25 18:12:39,392 nonebot] INFO: Scheduler started
[2021-09-25 18:12:39,393] Running on http://127.0.0.1:5700 (CTRL + C to quit)
```
色图功能是依赖绅士仓库的吗？群消息无法响应，私聊就可以，知道什么原因吗？目前是搭建在国内的服务器，有些功能无法回应，不知道是不是这个原因？最后再问问能写个详细的搭建文档吗？现在都不知道想要哪些功能得配置什么账号

**Comment by sola614** [comment]
我全部删了之后又重新装了一遍，这次群消息有响应了，不过有些功能提示没有权限（例如!色图），需要怎么弄？!K线也无法使用，如果我要在国内服务器要实现油管和推特的功能有代理配置的功能吗？还有就是我启动的时候还是报有错误
```
python3 ./qq_bot_core.py 
[2021-09-25 21:22:44,174 nonebot] ERROR: Failed to import and load "awesome.plugins.notice_handler", error: cannot import name 'notice_handler' from partially initialized module 'awesome.plugins.notice_handler' (most likely due to a circular import) (/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py)
[2021-09-25 21:22:44,174 nonebot] ERROR: cannot import name 'notice_handler' from partially initialized module 'awesome.plugins.notice_handler' (most likely due to a circular import) (/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py", line 1, in <module>
    from . import notice_handler
ImportError: cannot import name 'notice_handler' from partially initialized module 'awesome.plugins.notice_handler' (most likely due to a circular import) (/root/qqbot/qqBot-2.0.0/awesome/plugins/notice_handler/__init__.py)
[2021-09-25 21:22:46,108 nonebot] INFO: Succeeded to import and load "awesome.plugins.admin_setting"
[2021-09-25 21:22:46,616 nonebot] INFO: Succeeded to import and load "awesome.plugins.games"
[2021-09-25 21:22:47,111 nonebot] INFO: Succeeded to import and load "awesome.plugins.setu"
[2021-09-25 21:22:47,112 nonebot] INFO: Succeeded to import and load "awesome.plugins.natural_language"
[2021-09-25 21:22:47,119 nonebot] ERROR: Failed to import and load "awesome.plugins.little_helper", error: No module named 'Services.okex'
[2021-09-25 21:22:47,119 nonebot] ERROR: No module named 'Services.okex'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/little_helper/__init__.py", line 1, in <module>
    from . import little_helper
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/little_helper/little_helper.py", line 10, in <module>
    from Services.stock import Stock, Crypto
  File "/root/qqbot/qqBot-2.0.0/Services/stock.py", line 12, in <module>
    import Services.okex.spot_api as spot
ModuleNotFoundError: No module named 'Services.okex'
[2021-09-25 21:22:47,148 nonebot] ERROR: Failed to import and load "awesome.plugins.get_tweet", error: cannot import name 'SHARE_LINK' from 'config' (/root/qqbot/qqBot-2.0.0/config.py)
[2021-09-25 21:22:47,148 nonebot] ERROR: cannot import name 'SHARE_LINK' from 'config' (/root/qqbot/qqBot-2.0.0/config.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 404, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/get_tweet/__init__.py", line 1, in <module>
    from . import get_tweet
  File "/root/qqbot/qqBot-2.0.0/awesome/plugins/get_tweet/get_tweet.py", line 15, in <module>
    from config import SUPER_USER, DOWNLODER_FILE_NAME, SHARE_LINK, PATH_TO_ONEDRIVE
ImportError: cannot import name 'SHARE_LINK' from 'config' (/root/qqbot/qqBot-2.0.0/config.py)
[2021-09-25 21:22:47,149 nonebot] INFO: Succeeded to import and load "awesome.plugins.shadiao"
[2021-09-25 21:22:47,149 nonebot] INFO: Succeeded to import and load "awesome.plugins.chitchat"
[2021-09-25 21:22:47,149 nonebot] WARNING: Plugins successfully installed.
[2021-09-25 21:22:47,150 nonebot] INFO: Running on 127.0.0.1:5700
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: True
 * Running on http://127.0.0.1:5700 (CTRL + C to quit)
[2021-09-25 21:22:47,153 nonebot] INFO: Scheduler started
[2021-09-25 21:22:47,154] Running on http://127.0.0.1:5700 (CTRL + C to quit)
[2021-09-25 21:22:49,078] 127.0.0.1:50272 GET /ws/ 1.1 101 - 1876
[2021-09-25 21:22:49,080] INFO in __init__: received event: meta_event.lifecycle.connect
[2021-09-25 21:22:49,080] INFO in __init__: received event: meta_event.heartbeat
[2021-09-25 21:22:52,073] INFO in __init__: received event: meta_event.heartbeat
```

**Comment by remiliacn** [comment]
看起来像是配置文件不全啊
`ImportError: cannot import name 'SHARE_LINK' from 'config' (/root/qqbot/qqBot-2.0.0/config.py)`
你的根目录有个config.py的文件么，那里面有程序的大部分配置。如果没有的话就运行不了。

**Comment by sola614** [comment]
有的，根目录：
![IS61E6Q((CR_TOH_2W`_B](https://user-images.githubusercontent.com/36149249/134790123-551c3c21-e5b3-4a1b-8eb7-7d45bafeaaab.png)
然后config.py配置：
![1ZG4MO1$3%7M}ISTCZ@%~ V](https://user-images.githubusercontent.com/36149249/134790145-ca5b1ed7-7ffb-4a80-83b2-94df658b2978.png)

**Comment by remiliacn** [comment]
色图的权限要用`！删除色图禁用`的命令把那个群的色图禁用设定关掉（默认是新加入的群禁用色图功能的）

**Comment by remiliacn** [comment]
其它问题试一下最新的commit

https://github.com/remiliacn/qqBot/commit/8f7da641cfe1371f3bd5b3b55bb19f865c55c4f4

**Comment by sola614** [comment]
我clone了最新代码，然后安装依赖有报错，执行也有报错了，我分别用python3.7和python3.9版本安装都报错，报错如下：
![python3 7](https://user-images.githubusercontent.com/36149249/134889430-a869ba32-a032-4c06-8b27-9d754bc5c26f.png)
![3 9-1](https://user-images.githubusercontent.com/36149249/134889449-a16e235f-9d1b-4c16-9a94-883430efffe9.png)
![3 9](https://user-images.githubusercontent.com/36149249/134889453-aa6528df-6439-4f18-8654-526ef5e7a457.png)

文字版：  
依赖报错：
```
requests 2.24.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.7 which is incompatible.
aiocqhttp 1.3.0 requires Quart<0.12,>=0.11, but you'll have quart 0.15.1 which is incompatible
```
运行报错：
```
[root@VM8563 qqBot]# python3.9 ./qq_bot_core.py 
Traceback (most recent call last):
  File "/root/bot/qqBot/./qq_bot_core.py", line 5, in <module>
    import nonebot
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 5, in <module>
    import aiocqhttp
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 21, in <module>
    from .api_impl import (AsyncApi, SyncApi, HttpApi, WebSocketReverseApi,
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 19, in <module>
    from quart.wrappers.request import Websocket
ImportError: cannot import name 'Websocket' from 'quart.wrappers.request' (/usr/local/lib/python3.9/site-packages/quart/wrappers/request.py)

```

**Comment by remiliacn** [comment]
看log应该是有些依赖你的版本太低的原因。
